name: mingw-w64-x86_64-git

on:
  repository_dispatch:
    types:
      - mingw-w64-x86_64-git

env:
  GIT_CONFIG_PARAMETERS: "'user.name=${{github.actor}}' 'user.email=${{github.actor}}@users.noreply.github.com'"
  HOME: "${{github.workspace}}\\home"
  MSYSTEM: MINGW64
  PACKAGER: ${{github.actor}} <${{github.actor}}@users.noreply.github.com>
  USERPROFILE: "${{github.workspace}}\\home"

jobs:
  bundle-artifacts:
    runs-on: windows-latest
    steps:
      - name: Download git-sdk-64-build-installers
        shell: bash
        run: |
          a=git-sdk-64-build-installers && mkdir -p $a && curl -# https://wingit.blob.core.windows.net/ci-artifacts/$a.tar.xz | tar -C $a -xJf - &&
          mkdir -p home &&
          git config --global windows.sdk32.path '' &&
          git config --global windows.sdk64.path "$PWD/$a"
      - name: Clone build-extra
        run: git clone --single-branch -b master https://github.com/git-for-windows/build-extra git-sdk-64-build-installers\usr\src\build-extra
      - name: Generate bundle artifacts
        shell: powershell
        run: |
          & .\git-sdk-64-build-installers\git-cmd.exe --command=usr\bin\bash.exe -lc @"
            printf '#!/bin/sh\n\nexec /mingw64/bin/git.exe "`$@"\n' >/usr/bin/git &&
            mkdir -p bundle-artifacts &&

            git init --bare &&
            git remote add -f origin https://github.com/git-for-windows/git &&
            git fetch https://github.com/${{github.repository}} ${{github.ref}}:${{github.ref}} &&

            tag_name=\"`$(git describe --match 'v[0-9]*' FETCH_HEAD)-`$(date +%Y%m%d%H%M%S)\" &&
            echo \"prerelease-`${tag_name#v}\" >bundle-artifacts/ver &&
            echo \"`${tag_name#v}\" >bundle-artifacts/display_version &&
            echo \"`$tag_name\" >bundle-artifacts/next_version &&
            git tag -m \"Snapshot build\" \"`$tag_name\" FETCH_HEAD &&
            git bundle create bundle-artifacts/git.bundle origin/master..\"`$tag_name\" &&

            sh -x /usr/src/build-extra/please.sh mention feature \"Snapshot of `$(git show -s  --pretty='tformat:%h (%s, %ad)' --date=short FETCH_HEAD)\" &&
            git -C /usr/src/build-extra bundle create \"`$PWD/bundle-artifacts/build-extra.bundle\" origin/master..master
          "@
      - name: 'Publish Pipeline Artifact: bundle-artifacts'
        uses: actions/upload-artifact@v1
        with:
          name: bundle-artifacts
          path: bundle-artifacts
  pkg-x86_64:
    runs-on: windows-latest
    needs: bundle-artifacts
    steps:
      - name: Download git-sdk-64-makepkg-git
        shell: bash
        run: a=git-sdk-64-makepkg-git && mkdir -p $a && curl -# https://wingit.blob.core.windows.net/ci-artifacts/$a.tar.xz | tar -C $a -xJf -
      - name: Download bundle-artifacts
        uses: actions/download-artifact@v1
        with:
          name: bundle-artifacts
          path: bundle-artifacts
      - name: Check out build-extra/git and git/git
        run: |
          .\git-sdk-64-makepkg-git\usr\bin\bash.exe -lc @"
            git clone --depth=10 --single-branch -b master https://github.com/git-for-windows/build-extra /usr/src/build-extra &&
            git -C /usr/src/build-extra pull \"`$PWD\"/bundle-artifacts/build-extra.bundle master &&

            set -x &&
            git init &&
            git remote add -f origin https://github.com/git-for-windows/git &&
            git fetch --tags bundle-artifacts/git.bundle `$(cat bundle-artifacts/next_version) &&
            git reset --hard `$(cat bundle-artifacts/next_version)
          "@
      - name: Build mingw-w64-x86_64-git
        shell: powershell
        run: |
          & git-sdk-64-makepkg-git\usr\bin\sh.exe -lc @"
            set -x
            # Let `cv2pdb` find the DLLs
            PATH=\"`$PATH:/C/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64\"
            type -p mspdb140.dll || exit 1
            sh -x /usr/src/build-extra/please.sh build-mingw-w64-git --only-64-bit --build-src-pkg -o artifacts HEAD &&
            cp bundle-artifacts/ver artifacts/ &&

            b=`$PWD/artifacts &&
            version=`$(cat bundle-artifacts/next_version) &&
            (cd /usr/src/MINGW-packages/mingw-w64-git &&
            cp PKGBUILD.`$version PKGBUILD &&
            git commit -s -m \"mingw-w64-git: new version (`$version)\" PKGBUILD &&
            git bundle create \"`$b\"/MINGW-packages.bundle origin/master..master)
          "@
      - name: Publish mingw-w64-x86_64-git
        uses: actions/upload-artifact@v1
        with:
          name: pkg-x86_64
          path: artifacts
