name: CI/PR

on: [push, pull_request]

jobs:
  linux-clang:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      env:
        CC: clang
      run: |
        sudo apt-get update &&
        sudo apt-get -y install git gcc make libssl-dev libcurl4-openssl-dev libexpat-dev tcl tk gettext git-email zlib1g-dev apache2-bin &&
        ci/install-dependencies.sh
    - name: ci/run-build-and-test.sh
      env:
        CC: clang
      run: |
        ci/run-build-and-tests.sh || {
          ci/print-test-failures.sh
          exit 1
        }
